add_newline = false

# format="""
# $character 
# $custom
# """
# right_format = """$all"""

[character]
error_symbol = '[î‰](red)'
success_symbol = '[î‰](#78D6C6)'
vimcmd_symbol = '[î˜«](#C8E4B2)'
vimcmd_replace_one_symbol = '[î¬½](#DFCCFB)'
vimcmd_replace_symbol = '[ó°¬²](#DFCCFB)'
vimcmd_visual_symbol = '[ó°—˜](#ff5189)'

[directory]
style="#D4ADFC"

[battery]
full_symbol = ' ğŸ”‹ '
charging_symbol = ' âš¡ï¸ '
discharging_symbol = 'ó±Ÿ '

[[battery.display]]
threshold = 30
style = '#C70039'
discharging_symbol = 'ó±ƒ '


[cmd_duration]
min_time = 500
format = 'took [$duration](magenta) '
disabled=true

[git_branch]
style='#A8DF8E'
symbol = 'î‚ '
truncation_symbol = ''

[git_status]
style='#C3EDC0'
untracked = '[?$count](#7D7463)'
disabled=true

[git_commit]
commit_hash_length = 4
tag_symbol = 'îœ© '


[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[ğŸ’ PICKING](bold red)'
merge='[â›™ merging]'

[package]
format = 'by [ó°– $version](#9EB384) '

[sudo]
style = 'bold green'
symbol = 'ó°‡„ â€'
disabled = false

[lua]
format = 'via [î˜  $version](bold blue) '

[c]
format = 'via [î˜ $version](bold blue) '

[java]
format = 'via [î‰– $version](#C70039) '
