add_newline = true

# format="""
# $character
# $custom
# """
# right_format = """$all"""

[character]
error_symbol = '[ïƒš](red)'
success_symbol = '[ïƒš](#B4B4B8)'
vimcmd_symbol = '[ïƒ™](#C8E4B2)'
vimcmd_replace_one_symbol = '[î¬½](#DFCCFB)'
vimcmd_replace_symbol = '[ó°¬²](#DFCCFB)'
vimcmd_visual_symbol = '[ó°—˜](#ff5189)'

[directory]
style="#BFCCB5"

[battery]
full_symbol = ' ğŸ”‹ '
charging_symbol = ' âš¡ï¸ '
discharging_symbol = 'ó±Ÿ '

[[battery.display]]
threshold = 30
style = '#C70039'
discharging_symbol = 'ó±ƒ '


[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "â€‹"
untracked = "â€‹"
modified = "â€‹"
staged = "â€‹"
renamed = "â€‹"
deleted = "â€‹"
stashed = "â‰¡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[package]
format = '[ó°– $version](#9EB384) '

[sudo]
style = 'bold green'
symbol = 'ó°‡„  '
disabled = false

[lua]
format = '[î˜  $version]($style) '
style = "#A8A196"

[c]
format = '[î˜ $version]($style) '
style = "#A8A196"

[java]
format = '[î‰– $version]($style) '
style = "#A8A196"

[python]
format = "[îœ¼ $version]($style) "
style = "#A8A196"

[ruby]
format = "[î‘ $version]($style) "
style = "red"
detect_variables = ['RBENV_VERSION']
# disabled = true
